run:
  go: '1.18'
  tests: false

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

linters:
  enable:
    - bodyclose
    - dupl
    - exportloopref
    - goconst
    - godot
    - godox
    - goimports
    - revive
    - goprintffuncname
    - gosec
    - ifshort
    - misspell
    - prealloc
    - rowserrcheck
    - sqlclosecheck
    - unconvert
    - unparam
    - whitespace
